/* Cable: CMake Bootstrap Library.
 * Copyright 2018 Pawel Bylica.
 * Licensed under the Apache License, Version 2.0. See the LICENSE file.
 */

/* Generated by Cable Build Info on 2021-06-14T00:06:28. Do not modify directly. */

#include "buildinfo.h"

const struct buildinfo* nsfminer_get_buildinfo()
{
    static const struct buildinfo buildinfo = {
        .project_name = "nsfminer",
        .project_version = "1.3.14+commit.68afdc3c.dirty",
        .project_name_with_version = "nsfminer-1.3.14+commit.68afdc3c.dirty",
        .git_commit_hash = "68afdc3c34efb738be0b65c4acb4fda81e71a265",
        .system_name = "darwin",
        .system_processor = "x86_64",
        .compiler_id = "appleclang",
        .compiler_version = "12.0.5.12050022",
        .build_type = "release",
    };
    return &buildinfo;
}
